# Generated by Django 4.2 on 2026-05-12 06:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Userapp', '0002_note_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='note',
            name='password',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
